# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  # api_password: YOUR_SECRET_PASSWORD
  # ssl_certificate: certificate.pem
  # ssl_key: privkey.pem
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.167.5
    
homeassistant:
  name: Roubenka
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  country: CZ
  time_zone: Europe/Prague
  currency: CZK
  external_url: !secret external_url
  internal_url: !secret internal_url
  allowlist_external_dirs:
    - "/tmp"

# Text to speech
tts:
  - platform: google_translate

logger:
  default: info
  logs: 
    custom_components.jablotron100: debug


automation: !include_dir_merge_list automation
scene: !include_dir_merge_list scene
script: !include_dir_merge_named script
sensor: !include_dir_merge_list sensor
group: !include groups.yaml

recorder:
  db_url: !secret mariadb
  purge_keep_days: 10   # default


influxdb:
  api_version: 2
  ssl: true
  host: !secret influx_host
  port: 443
  token: !secret influx_token
  organization: !secret influx_organization
  bucket: home_assistant
  tags:
    source: HA
  tags_attributes:
    - friendly_name
  default_measurement: units


template:
  - trigger:
      - platform: state
        entity_id:
          - binary_sensor.motion_detector_device_4_motion
          - binary_sensor.motion_detector_device_5_motion
          - binary_sensor.motion_detector_device_6_motion
          - binary_sensor.motion_detector_device_7_motion
        to: 'on'
    sensor:
      - unique_id: last_pir_motion_sensor_triggered
        name: Posledni detekovany pohyb
        icon: mdi:motion-sensor
        state: >
          {{trigger.to_state.name}}
        attributes:
          entity_id: >
            {{trigger.entity_id}}

binary_sensor:
  - platform: ping
    name: "Sypka reachability"
    host: 192.168.167.5
    scan_interval: 10


sql:
# find entry with state 'on' old at least 30s
  - name: pir_terasa_older_30s
    query: >
          SELECT
            last_updated_ts
          FROM
            states
            INNER JOIN states_meta ON
              states.metadata_id = states_meta.metadata_id
          WHERE
            states_meta.entity_id = 'binary_sensor.door_opening_detector_device_24_door'
            AND last_updated_ts <= UNIX_TIMESTAMP(NOW() - INTERVAL 30 SECOND)
            AND state = 'on'
          ORDER BY
            last_updated_ts DESC
          LIMIT
            1;
    column: "last_updated_ts"
  - name: pir2_terasa_older_30s
    query: >
          SELECT
            last_updated_ts
          FROM
            states
            INNER JOIN states_meta ON
              states.metadata_id = states_meta.metadata_id
          WHERE
            states_meta.entity_id = 'binary_sensor.0x001788010df74198_occupancy'
            AND last_updated_ts <= UNIX_TIMESTAMP(NOW() - INTERVAL 30 SECOND)
            AND state = 'on'
          ORDER BY
            last_updated_ts DESC
          LIMIT
            1;
    column: "last_updated_ts"

notify:
  - platform: msteams
    name: ms_teams_petr
    url: !secret msteams_url

  - platform: clicksend
    name: clicksend_petr
    username: !secret petr_email
    api_key: !secret clicksend_api_key
    recipient: !secret petr_phone
  - platform: clicksend
    name: clicksend_petra
    username: !secret petr_email
    api_key: !secret clicksend_api_key
    recipient: !secret petra_phone

timer:
  led_schody:
    duration: "00:00:30"
  led_loznice:
    duration: "00:00:30"
