- alias: "Nocni hlidac - pohyb na terase"
  trigger:
    - platform: state
      entity_id: binary_sensor.door_opening_detector_device_24_door
      to: 'on'
  condition:   
    - condition: state
      entity_id: "alarm_control_panel.section_1"
      state: "disarmed"
    - condition: state
      entity_id: "binary_sensor.motion_detector_device_4_motion"    # vstupni chodba PIR
      state: "off"
      for:
        minutes: 3
    - condition: state
      entity_id: "binary_sensor.motion_detector_device_5_motion"    # obyvak PIR
      state: "off"
      for:
        minutes: 3
    - alias: "PIR was idle for certain time (180s) before trigger" # PIR terasa, aby se vyloucilo, kdyz tam nekdo v noci neco dela
      condition: template
      value_template: "{{  ((now() | as_timestamp() | int(0)) - (states('sensor.pir_terasa_older_30s') | int(0))) > 180  }}"


  action:       # spust Zigbee alarm
    - service: mqtt.publish
      data:
        topic: zigbee2mqtt/0x847127fffe096bc3/set
        payload: '{"volume": 0}'
    - service: mqtt.publish
      data:
        topic: zigbee2mqtt/0x847127fffe096bc3/set
        payload: '{"volume": 7}'
    - service: mqtt.publish
      data:
        topic: zigbee2mqtt/0x847127fffe096bc3/set
        payload: '{"warning": {"mode": "emergency_panic", "level": "high", "strobe_level": "low", "strobe": "false", "strobe_duty_cycle": 0, "duration": 1}}'
    - delay:
        seconds: 30
    - service: mqtt.publish
      data:
        topic: zigbee2mqtt/0x847127fffe096bc3/set
        payload: '{"warning": {"mode": "stop", "level": "low", "strobe_level": "low", "strobe": "false", "strobe_duty_cycle": 1, "duration": 1}}'

