- alias: "Zapnuti svetla v loznici po zapadu slunce"
  description: ""
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      attribute: elevation
      # Can be a positive or negative number
      below: -2.0
  condition: 
    - condition: state
      entity_id: "group.presence_home"
      state: "not_home"
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.shelly1_40f520169505

- alias: "Vypnuti svetla v loznici ve stanoveny cas"
  description: ""
  trigger:
    - platform: time
      at: "18:10:00"
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.shelly1_40f520169505

- alias: "Zapnuti svetla v pokojicku ve stanoveny cas"
  description: ""
  trigger:
    - platform: time
      at: "21:09:00"
  condition: 
    - condition: state
      entity_id: "group.presence_home"
      state: "not_home"
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.shellyplus1_7c87ce592550

- alias: "Vypnuti svetla v pokojicku ve stanoveny cas"
  description: ""
  trigger:
    - platform: time
      at: "22:01:00"
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.shellyplus1_7c87ce592550

- alias: "Zapnuti fake televize"
  description: ""
  trigger:
    - platform: time
      at: "17:10:00"
  condition: 
    - condition: state
      entity_id: "group.presence_home"
      state: "not_home"
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.shellyplus1pm_3c6105726160
    
- alias: "Vypnuti fake televize"
  description: ""
  trigger:
    - platform: time
      at: "21:50:00"
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.shellyplus1pm_3c6105726160