- alias: "Zapnuti plasice kun"
  description: ""
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      attribute: elevation
      # Can be a positive or negative number
      below: -6.0
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.shellyplug_s_21752f

- alias: "Vypnuti plasice kun"
  description: ""
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      attribute: elevation
      above: -3.0
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.shellyplug_s_21752f